# Generated by Django 4.1.7 on 2023-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangulo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformador',
            name='C2H2',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='C2H4',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='C2H6',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='CH4',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='H2',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
