# Generated by Django 4.1.7 on 2023-03-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangulo_app', '0002_transformador_c2h2_transformador_c2h4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transformador',
            name='C2H2',
        ),
        migrations.RemoveField(
            model_name='transformador',
            name='C2H4',
        ),
        migrations.RemoveField(
            model_name='transformador',
            name='C2H6',
        ),
        migrations.RemoveField(
            model_name='transformador',
            name='CH4',
        ),
        migrations.RemoveField(
            model_name='transformador',
            name='H2',
        ),
        migrations.AddField(
            model_name='transformador',
            name='C2H2ppm',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='C2H4ppm',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='C2H6ppm',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='CH4ppm',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transformador',
            name='H2ppm',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
