# Generated by Django 4.1.7 on 2023-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangulo_app', '0003_remove_transformador_c2h2_remove_transformador_c2h4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformador',
            name='t1fallas',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='transformador',
            name='nombre',
            field=models.CharField(default='', max_length=15),
        ),
    ]
