# Generated by Django 4.1.7 on 2023-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangulo_app', '0004_transformador_t1fallas_alter_transformador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformador',
            name='t4fallas',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='transformador',
            name='t5fallas',
            field=models.CharField(default='', max_length=2),
        ),
    ]
