# Generated by Django 4.1.7 on 2023-04-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triangulo_app', '0007_transformador_fecha_alter_transformador_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='transformador',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triangulo_app.nombre'),
        ),
    ]
